# Generated by Django 2.0 on 2018-12-15 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AddLecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='CompanyName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=20)),
                ('Designation', models.TextField(max_length=50)),
                ('Field_of_Experience', models.IntegerField()),
                ('Skill', models.TextField(max_length=50)),
                ('Personal_Email', models.TextField(max_length=20)),
                ('mobile', models.IntegerField()),
                ('about', models.TextField(max_length=100)),
                ('password', models.TextField(max_length=20)),
                ('Icard_Picture', models.TextField(null=True)),
                ('CompanyName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bridge.CompanyName')),
            ],
        ),
        migrations.CreateModel(
            name='Expert_Following',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Is_follow', models.TextField(max_length=20)),
                ('Is_follow_accepted', models.TextField(max_length=20)),
                ('Expert_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bridge.Expert')),
            ],
        ),
        migrations.CreateModel(
            name='Expert_Student_Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_block', models.TextField()),
                ('Expert_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bridge.Expert')),
            ],
        ),
        migrations.CreateModel(
            name='LectureHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_count', models.IntegerField()),
                ('student_list', models.TextField()),
                ('lecture_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bridge.AddLecture')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_id', models.IntegerField()),
                ('name', models.TextField(max_length=20)),
                ('Collage', models.TextField(max_length=50)),
                ('Year_Experience', models.IntegerField()),
                ('Qualification', models.TextField(max_length=50)),
                ('Personal_Email', models.TextField(max_length=20)),
                ('mobile', models.IntegerField()),
                ('Profile_piture', models.TextField()),
                ('password', models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Student_block_count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_count', models.IntegerField()),
                ('Student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bridge.Student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentLectureAttended',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expert_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bridge.Expert')),
                ('lecture_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bridge.AddLecture')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bridge.Student')),
            ],
        ),
        migrations.CreateModel(
            name='User_Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserComapny',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bridge.CompanyName')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='expert_student_block',
            name='Student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bridge.Student'),
        ),
        migrations.AddField(
            model_name='expert_following',
            name='Student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bridge.Student'),
        ),
        migrations.AddField(
            model_name='addlecture',
            name='expert_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bridge.Expert'),
        ),
    ]
