# Generated by Django 2.0 on 2019-01-09 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='Profile_piture',
            field=models.FileField(default='new.jpg', upload_to='templates'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expert',
            name='Icard_Picture',
            field=models.FileField(default='new.jpg', upload_to='templates'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expert',
            name='Personal_Email',
            field=models.EmailField(max_length=20),
        ),
    ]
