# Generated by Django 2.0 on 2019-01-09 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0002_auto_20190109_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expert',
            name='Icard_Picture',
            field=models.ImageField(blank=True, null=True, upload_to='templates'),
        ),
        migrations.AlterField(
            model_name='expert',
            name='Profile_piture',
            field=models.ImageField(blank=True, null=True, upload_to='templates'),
        ),
    ]
