# Generated by Django 2.0 on 2019-01-09 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0003_auto_20190109_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expert',
            name='Designation',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='expert',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='expert',
            name='password',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='Collage',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='Personal_Email',
            field=models.EmailField(max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='Profile_piture',
            field=models.ImageField(blank=True, null=True, upload_to='templates'),
        ),
        migrations.AlterField(
            model_name='student',
            name='Qualification',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(max_length=20),
        ),
    ]
