# Generated by Django 2.0 on 2019-01-09 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0004_auto_20190109_2311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Student_id',
        ),
    ]
