# Generated by Django 2.0 on 2019-01-12 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0005_remove_student_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expert',
            name='Skill',
            field=models.CharField(max_length=200),
        ),
    ]
