# Generated by Django 2.0 on 2019-01-12 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0011_auto_20190112_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expert',
            name='Icard_Picture',
            field=models.FileField(blank=True, null=True, upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='expert',
            name='Profile_piture',
            field=models.FileField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
