# Generated by Django 2.0 on 2019-01-12 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0012_auto_20190112_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addlecture',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
