# Generated by Django 2.0 on 2019-01-12 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0013_auto_20190112_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addlecture',
            name='expert_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bridge.Expert'),
        ),
    ]
