# Generated by Django 2.0 on 2019-01-19 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0014_auto_20190112_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Profile_piture',
            field=models.FileField(blank=True, null=True, upload_to='templates'),
        ),
    ]
