# Generated by Django 2.0 on 2019-01-19 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0015_auto_20190119_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Profile_piture',
            field=models.FileField(blank=True, null=True, upload_to='profile_images'),
        ),
    ]
