# Generated by Django 2.0 on 2019-01-20 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0016_auto_20190120_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Profile_piture',
            field=models.FileField(blank=True, null=True, upload_to='profile/'),
        ),
    ]
