# Generated by Django 2.0 on 2019-01-21 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0021_commonnews'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonnews',
            name='student_id',
            field=models.IntegerField(null=True),
        ),
    ]
