# Generated by Django 2.0 on 2019-01-22 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0022_commonnews_student_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonExpertNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news', models.TextField(null=True)),
                ('expert_id', models.IntegerField(null=True)),
            ],
        ),
    ]
