# Generated by Django 2.0 on 2019-01-26 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0023_commonexpertnews'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertOnlineStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_online', models.BooleanField(default=False)),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bridge.Expert')),
            ],
        ),
    ]
