# Generated by Django 2.0 on 2019-01-26 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0024_expertonlinestatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonexpertnews',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
    ]
