# Generated by Django 2.0 on 2019-01-26 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0025_commonexpertnews_is_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news', models.TextField()),
            ],
        ),
    ]
