# Generated by Django 2.0 on 2019-01-26 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0026_newsfeed'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsfeed',
            name='expert_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='newsfeed',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
    ]
