# Generated by Django 2.0 on 2019-01-26 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0027_auto_20190126_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expert',
            name='Company_Name',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='usercomapny',
            name='company_id',
            field=models.TextField(max_length=50),
        ),
        migrations.DeleteModel(
            name='CompanyName',
        ),
    ]
