# Generated by Django 2.0 on 2019-01-27 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0028_auto_20190126_1302'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('communication_skill', models.IntegerField()),
                ('domain_knowledge', models.IntegerField()),
                ('team_skill', models.IntegerField()),
                ('as_boss', models.IntegerField()),
                ('leadership', models.IntegerField()),
            ],
        ),
    ]
