# Generated by Django 2.0 on 2019-01-27 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0030_studentreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertreview',
            name='overall',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentreview',
            name='overall',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
