# Generated by Django 2.0 on 2019-01-27 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0031_auto_20190127_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertreview',
            name='expert',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bridge.Expert'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentreview',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bridge.Student'),
            preserve_default=False,
        ),
    ]
