# Generated by Django 2.0 on 2019-02-03 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0032_auto_20190127_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expert',
            name='Company_Name',
            field=models.CharField(max_length=200),
        ),
    ]
