# Generated by Django 2.0 on 2019-02-03 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0033_auto_20190203_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='Department',
            field=models.CharField(choices=[('management', 'MANAGEMENT'), ('engineering', 'ENGINEERING'), ('pharamacy', 'PHARAMACY'), ('other', 'OTHER')], default='other', max_length=4),
        ),
    ]
