# Generated by Django 2.0 on 2019-02-09 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0039_e2e'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturehistory',
            name='expert_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='bridge.Expert'),
            preserve_default=False,
        ),
    ]
