# Generated by Django 2.0 on 2019-02-09 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0040_lecturehistory_expert_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expertreview',
            name='communication_skill',
        ),
        migrations.RemoveField(
            model_name='expertreview',
            name='domain_knowledge',
        ),
        migrations.RemoveField(
            model_name='expertreview',
            name='leadership',
        ),
        migrations.RemoveField(
            model_name='expertreview',
            name='overall',
        ),
        migrations.RemoveField(
            model_name='expertreview',
            name='team_skill',
        ),
        migrations.AddField(
            model_name='expertreview',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bridge.Student'),
            preserve_default=False,
        ),
    ]
