# Generated by Django 2.0 on 2019-02-09 17:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0041_auto_20190209_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='addlecture',
            name='update_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 9, 23, 6, 9, 400714)),
        ),
    ]
