# Generated by Django 2.0 on 2019-02-09 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0042_addlecture_update_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addlecture',
            name='update_timestamp',
        ),
    ]
