# Generated by Django 2.0 on 2019-02-09 17:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0043_remove_addlecture_update_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='addlecture',
            name='update_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 9, 23, 15, 23, 73460)),
        ),
    ]
