# Generated by Django 2.0 on 2019-02-09 19:26

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0044_addlecture_update_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addlecture',
            name='update_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 10, 0, 56, 6, 942348)),
        ),
        migrations.AlterField(
            model_name='expert',
            name='Field_of_Experience',
            field=models.IntegerField(default=7, validators=[django.core.validators.MinValueValidator(7), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
