# Generated by Django 2.0 on 2019-02-09 19:27

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0045_auto_20190210_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addlecture',
            name='update_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 10, 0, 57, 9, 929991)),
        ),
        migrations.AlterField(
            model_name='expert',
            name='mobile',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(15)]),
        ),
    ]
