# Generated by Django 2.0 on 2019-02-09 19:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0047_auto_20190210_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addlecture',
            name='update_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 10, 0, 59, 20, 310630)),
        ),
        migrations.AlterField(
            model_name='expert',
            name='mobile',
            field=models.IntegerField(max_length=15),
        ),
    ]
