# Generated by Django 2.0 on 2019-02-10 05:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0049_auto_20190210_1112'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='addlecture',
            name='update_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 10, 11, 20, 17, 462878)),
        ),
    ]
