# Generated by Django 2.0 on 2019-02-10 06:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0050_auto_20190210_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminnews',
            name='expert',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bridge.Expert'),
        ),
        migrations.AddField(
            model_name='adminnews',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bridge.Student'),
        ),
        migrations.AlterField(
            model_name='addlecture',
            name='update_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 10, 11, 59, 41, 70586)),
        ),
    ]
